### ISSUE TITLE
Wrong length of city_indices in instructing combining city_indices and city_names

### ISSUE THREAD

**Issue by lpchu** [learn-co-curriculum/python-for-loops-lab#11]
In the exercise combining city_indices and city_names, the instruction said city_indices is generated by list(range(1,12)), which will generate a list of numbers from 1 to 11. 

Combining this city_indices and city_names will not work because the length of city_names is 12, so the length of city_indices should also be 12, and because it starts from 1 instead of 0, it should go from 1 to 12 (so the code for generating the city_indices should be list(range(1,13)) ), instead of 1 to 11 as in the instruction.

**Comment by LoreDirick** [comment]
@lpchu thanks for raising, I changed "1-11" to"0-11". Thanks!
