### ISSUE TITLE
Incorrect numbers in solution

### ISSUE THREAD

**Issue by robblatt** [learn-co-curriculum/python-for-loops-lab#13]
city_areas should be [4758, 2731, 3194, 200, 491, 3750, 68, 8300, 33, 27, 59, 672]
city_areas is currently [4758, 2731571, 3194, 200, 491, 3750, 68, 8300, 33, 27, 59, 672]

**Comment by mas16** [comment]
Hi robblatt, thank you for pointing this out. The city_areas values have been updated.
