### ISSUE TITLE
Loops Lab

### ISSUE THREAD

**Issue by ThoaShook** [learn-co-curriculum/python-for-loops-lab#14]
For the Loops Lab. In Input [6] I got the Output correct 1. Buenos Aires; 2. Toronto; 3. Pyeongchang; ....12. Iguazu Falls. However, the next input [7] names_and ranks[0], names_and_ranks[1], names_and_ranks[-1], I got error message "list index out of range". Not sure why it is the case, because in a previous input I have assigned city_indices = list(range(0,len(cities))). Please help. Thanks

**Comment by mas16** [comment]
Hi ThoaShook, thanks for posting! I'd recommend reviewing the code you wrote for populating the names_and_ranks list. If you get totally stuck, you can consult the solutions for further clarification.
