### ISSUE TITLE
Importing data from Excel - Question about syntax

### ISSUE THREAD

**Issue by muqhtar-dev** [learn-co-curriculum/python-for-loops-lab#21]
import pandas
file_name = './cities.xlsx'
travel_df = pandas.read_excel(file_name)
cities = travel_df.to_dict('records')

In the last line of the above code, I understand that we're converting travel_df to a dictionary names 'cities'.

What does 'record' stand for? I don't understand this despite seeing this piece of code multiple times.

Thank you.

**Comment by ismayc** [comment]
`'records'` corresponds to the `orient` argument of `.to_dict()`. More info [here](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_dict.html) on the `.to_dict()` documentation.
