### ISSUE TITLE
Solution to combing city_indices and city_names

### ISSUE THREAD

**Issue by Socjon** [learn-co-curriculum/python-for-loops-lab#5]
I had a question concerning the solution when ask to 
"...assign the variable names_and_ranks to a list, with each element equal to the city name and it's corresponding rank."

The solution: 
```
names_and_ranks = [] # make sure the list is empty
for index in city_indices: 
    names_and_ranks.append(f"{index + 1}. {city_names[index]}")
names_and_ranks
```
My concern comes after the `.append`, what does that `f` do exactly? I don't recall that being covered in the previous lessons. If you can point to where I missed it, I would appreciate it.

Thanks

**Comment by cutterbuck** [comment]
good call @Socjon -  Thanks!
